# Pandas
#### https://www.packtpub.com/application-development/learning-pandas

In [1]:
import pandas as pd
import numpy as np

In [8]:
dates = pd.date_range('2018-01-01', '2018-01-07')
num = pd.Series([1, 2 , 5 ,5 , 6 ,7 ,1], index= dates)

In [14]:
num.quantile(.5)

5.0

In [17]:
array_to_sq = np.arange(0, 10000)
%timeit array_to_sq ** 2

8.34 µs ± 158 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
np.linspace(0, 5, 10, dtype = int)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 5])

In [5]:
np.arange(0, 10, 2, dtype= int)

array([0, 2, 4, 6, 8])

In [9]:

# create a 1x20 array, and reshape to a 5x4 2d-array
m = np.arange(0, 20).reshape(5, 4)
m



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
print(str(np.size(m, 0)) + ' x ' + str(np.size(m, 1)))

5 x 4


In [17]:
m[1, ]

array([4, 5, 6, 7])

In [19]:
m[:,1]

array([ 1,  5,  9, 13, 17])

In [24]:
a = np.arange(5)
a >= 2

array([False, False,  True,  True,  True], dtype=bool)

In [25]:
def exp (x):
   return x<3 or x>3
# np.vectorize applies the method to all items in an array
np.vectorize(exp)(a)

array([ True,  True,  True, False,  True], dtype=bool)

In [30]:
a[a> 2]

array([3, 4])

In [33]:
#print(np.sum(a[a>2]))
print(np.sum(a>2))

2


In [37]:
a1 = np.arange(9).reshape(3, 3)
a2 = np.arange(9, 0 , -1).reshape(3, 3)
a1 < a2

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]], dtype=bool)